import {
  Geist,
  Geist_Mono,
  Space_Mono,
} from "next/font/google";
import "./globals.css";
import { cn } from "@/app/lib/utils";
import localFont from "next/font/local";
import { StarsBackground } from "./components/Animations/stars";
import Header from "./components/Header";
import Footer from "./components/Sections/Footer";


const satoshi = localFont({
  src: "./fonts/Satoshi-Variable.ttf",
  variable: "--font-satoshi",
});

const spaceMoto = Space_Mono({
  variable: "--font-space-mono",
  subsets: ['latin'],
  weight: ["400", "700"]
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  // src: '.',
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ben Batres",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-scroll-behavior="smooth"
      className={cn(
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        satoshi.variable,
        spaceMoto.variable
      )}
    >
      <body className="relative min-h-screen">
        <div className="fixed inset-0 -z-10">
          <StarsBackground />
        </div>
        <main className="relative">
          <Header />
          {children}
          <Footer />
          </main>
      </body>
    </html>
  );
}
